"""Mock ADP generation — SYNTHETIC data for draft simulation.

WARNING: All ADP data generated by this module is MOCK/SYNTHETIC.
It is derived from model projections with platform-specific noise,
NOT from real platform draft data.
"""

from __future__ import annotations

import csv
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from .players import Player


@dataclass
class PlatformProfile:
    """Platform-specific ADP biases and noise parameters."""

    name: str
    qb_bias: float  # negative = drafted higher (lower ADP number)
    rb_bias: float
    wr_bias: float
    te_bias: float
    rookie_boost: float  # negative = drafted higher
    base_noise: float

    def position_bias(self, position: str) -> float:
        return {
            "QB": self.qb_bias,
            "RB": self.rb_bias,
            "WR": self.wr_bias,
            "TE": self.te_bias,
        }.get(position, 0.0)


PLATFORMS = {
    "sleeper": PlatformProfile("sleeper", qb_bias=0, rb_bias=1, wr_bias=-1, te_bias=0, rookie_boost=-4, base_noise=3.0),
    "espn": PlatformProfile("espn", qb_bias=-3, rb_bias=-1, wr_bias=1, te_bias=2, rookie_boost=0, base_noise=2.5),
    "yahoo": PlatformProfile("yahoo", qb_bias=1, rb_bias=0, wr_bias=-1, te_bias=1, rookie_boost=-2, base_noise=2.5),
}


def _is_young_player(player: Player) -> bool:
    """Heuristic: players with low pos_rank and no team, or very high ppg
    relative to games played, are likely young/rookie players."""
    # Use pos_rank <= 3 and high ppg as a rough proxy since we don't have years_exp
    # Also, players with empty team strings are often rookies entering the league
    if not player.team:
        return True
    # High projected_ppg relative to low projected_games suggests a young breakout
    if player.pos_rank <= 5 and player.projected_games < 14:
        return True
    return False


def generate_platform_adp(
    players: list[Player],
    platform: str,
    rng: np.random.Generator | None = None,
) -> list[tuple[Player, float]]:
    """Generate mock ADP rankings for a single platform.

    Args:
        players: List of players sorted by projected_total descending
        platform: Platform name (sleeper, espn, yahoo)
        rng: Random number generator for reproducibility

    Returns:
        List of (player, adp) tuples sorted by ADP ascending
    """
    if rng is None:
        rng = np.random.default_rng(42)

    profile = PLATFORMS[platform]

    adp_entries = []
    for base_rank, player in enumerate(players, start=1):
        # Position bias
        bias = profile.position_bias(player.position)

        # Rookie/young player boost
        rookie_mult = 2.0 if _is_young_player(player) else 1.0
        rookie_adj = profile.rookie_boost if _is_young_player(player) else 0.0

        # Noise scales with rank: higher-ranked players have tighter ADP
        noise_scale = profile.base_noise * (1 + 0.3 * math.log(base_rank)) * rookie_mult
        noise = rng.normal(0, noise_scale)

        adp = base_rank + bias + rookie_adj + noise
        adp = max(1.0, adp)  # ADP can't be below 1
        adp_entries.append((player, adp))

    # Sort by ADP
    adp_entries.sort(key=lambda x: x[1])
    return adp_entries


def generate_consensus_adp(
    players: list[Player],
    rng: np.random.Generator | None = None,
) -> list[tuple[Player, float]]:
    """Generate consensus ADP by averaging across all 3 platforms.

    Returns:
        List of (player, adp) tuples sorted by consensus ADP ascending
    """
    if rng is None:
        rng = np.random.default_rng(42)

    # Generate ADP for each platform with different but deterministic seeds
    platform_adps: dict[str, dict[str, float]] = {}
    for i, platform in enumerate(PLATFORMS):
        platform_rng = np.random.default_rng(rng.integers(0, 2**31) + i)
        entries = generate_platform_adp(players, platform, platform_rng)
        platform_adps[platform] = {p.name: adp for p, adp in entries}

    # Average ADP across platforms
    consensus = []
    for player in players:
        adps = [platform_adps[p][player.name] for p in PLATFORMS if player.name in platform_adps[p]]
        avg_adp = sum(adps) / len(adps) if adps else float("inf")
        consensus.append((player, avg_adp))

    consensus.sort(key=lambda x: x[1])
    return consensus


def write_adp_csvs(
    players: list[Player],
    output_dir: str | Path = "data/adp",
    seed: int = 42,
) -> dict[str, Path]:
    """Generate and write mock ADP CSVs for all platforms + consensus.

    Returns:
        Dict mapping platform name to output file path
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(seed)
    written = {}

    for platform in PLATFORMS:
        platform_rng = np.random.default_rng(rng.integers(0, 2**31))
        entries = generate_platform_adp(players, platform, platform_rng)
        path = output_dir / f"mock_{platform}.csv"
        _write_csv(entries, path, platform)
        written[platform] = path

    # Consensus
    consensus_rng = np.random.default_rng(seed)
    entries = generate_consensus_adp(players, consensus_rng)
    path = output_dir / "mock_consensus.csv"
    _write_csv(entries, path, "consensus")
    written["consensus"] = path

    return written


def _write_csv(
    entries: list[tuple[Player, float]], path: Path, platform: str
) -> None:
    """Write ADP entries to a CSV file with warning header."""
    with open(path, "w", newline="") as f:
        f.write(f"# WARNING: MOCK/SYNTHETIC ADP — not real {platform} platform data\n")
        writer = csv.writer(f)
        writer.writerow(["adp_rank", "player_name", "position", "team", "adp", "projected_total"])
        for rank, (player, adp) in enumerate(entries, start=1):
            writer.writerow([
                rank,
                player.name,
                player.position,
                player.team,
                f"{adp:.1f}",
                f"{player.projected_total:.0f}",
            ])


def load_adp(
    platform: str = "consensus",
    adp_dir: str | Path = "data/adp",
) -> dict[str, float]:
    """Load a mock ADP file into a name->adp dict.

    Returns:
        Dict mapping player name to ADP value
    """
    path = Path(adp_dir) / f"mock_{platform}.csv"
    if not path.exists():
        raise FileNotFoundError(f"ADP file not found: {path}. Run write_adp_csvs() first.")

    adp = {}
    with open(path, newline="") as f:
        # Skip warning comment line
        for line in f:
            if not line.startswith("#"):
                break
        # line is now the header row; re-read with DictReader
        reader = csv.DictReader(f, fieldnames=["adp_rank", "player_name", "position", "team", "adp", "projected_total"])
        for row in reader:
            if row["adp_rank"] == "adp_rank":
                continue  # skip header if encountered
            adp[row["player_name"]] = float(row["adp"])
    return adp
